"""Import gear facts from a local AutoBiS installation; never copy its UI/code.

Usage: python Tools/ImportAutoBiS.py <AutoBiS directory>
Requires the development dependencies in requirements-dev.txt.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

from lupa import LuaRuntime

ROOT = Path(__file__).resolve().parents[1]
SLOTS = {1: 'head', 2: 'neck', 3: 'shoulder', 5: 'chest', 6: 'waist',
         7: 'legs', 8: 'feet', 9: 'wrist', 10: 'hands', 11: 'ring',
         12: 'ring', 13: 'trinket', 14: 'trinket', 15: 'back',
         16: 'main-hand', 17: 'off-hand'}


def quote(value):
    return json.dumps(str(value), ensure_ascii=False)


def generate(directory):
    raw = (directory / 'AutoBiS_Data.lua').read_bytes()
    toc = (directory / 'AutoBiS.toc').read_text(encoding='utf-8-sig')
    version = re.search(r'^## Version:\s*(\S+)', toc, re.M).group(1)
    lua = LuaRuntime(unpack_returned_tuples=True, max_memory=16 * 1024 * 1024)
    ns = lua.table()
    # The declarative file gets no filesystem, OS, globals or addon UI APIs.
    lua.eval('''function(code, ns)
        local ticks=0
        debug.sethook(function() ticks=ticks+1; if ticks>100 then error('data instruction limit') end end, '', 10000)
        local ok,err=pcall(function() assert(load(code,'AutoBiS data','t',{}))('AutoBiS',ns) end)
        debug.sethook()
        if not ok then error(err) end
    end''')(raw.decode('utf-8-sig'), ns)
    date = str(ns.DataVersion)
    assert re.fullmatch(r'\d{4}-\d{2}-\d{2}', date), 'Missing data date'
    lines = ['local _, JP = ...', '-- Generated by Tools/ImportAutoBiS.py.',
             'JP.AutoBiSData = {', f'    updatedAt = {quote(date)}, version = {quote(version)},',
             '    source = "AutoBiS / Wowhead",',
             '    url = "https://www.curseforge.com/wow/addons/autobis",',
             f'    sha256 = {quote(hashlib.sha256(raw).hexdigest())},', '    specs = {']
    count = 0
    for spec_id, spec in sorted(ns.BiS.items()):
        # AutoBiS 1.2.1 ships a stale scraped ID; the existing Retail roster
        # (UpdateBiSData.ps1 / SeasonTop.lua) identifies Devourer as 1480.
        if spec.slug == 'demon-hunter/devourer':
            spec_id = 1480
        assert isinstance(spec_id, int) and spec_id > 0
        lines.append(f'        [{spec_id}] = {{ slug = {quote(spec.slug)}, variants = {{')
        for _, variant in sorted(spec.variants.items()):
            name = str(variant.name)
            context = 'mplus' if 'mythic+' in name.lower() else 'raid' if 'raid' in name.lower() else 'overall'
            lines.append(f'            {{ name = {quote(name)}, context = {quote(context)}, items = {{')
            seen = set()
            for _, item in sorted(variant['items'].items()):
                assert isinstance(item.id, int) and item.id > 0 and item.inv in SLOTS
                if item.id in seen:
                    continue
                seen.add(item.id)
                lines.append(f'                [{item.id}] = {{ slot = {quote(SLOTS[item.inv])}, name = {quote(item.name)}, dropSource = {quote(item.source or "")}, dropKind = {quote(item.kind or "")}, }},')
                count += 1
            assert seen, f'Empty variant: {spec.slug}/{name}'
            lines.append('            } },')
        lines.append('        } },')
    assert len(list(ns.BiS)) == 40, 'Unexpected spec coverage; review source before importing'
    lines += ['    },', '}', '']
    return '\n'.join(lines), count


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('directory', type=Path)
    args = parser.parse_args()
    content, count = generate(args.directory)
    output = ROOT / 'MythicBoost/Data/AutoBiS.lua'
    output.write_text(content, encoding='utf-8')
    print(f'Imported 40 specs / {count} gear entries into {output}')
